# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=&url=https%3A%2F%2Fsupport.plymouth.edu%2Fkb_images%2FYammer%2Fdefault.jpeg&psig=AOvVaw0laDRpnPC7b6i4W5to-iiO&ust=1509011045329166', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
