# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20171025_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
